In [13]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.externals import joblib
from sklearn.model_selection import ParameterGrid

/software/home/chenzh/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [18]:
# train
params_grid = {
    'learning_rate': [0.05,0.5],
    'n_estimators': [100],
    'subsample': [0.6],
    'colsample_bytree': [0.6,0.5],
    'max_depth': [7],
    'min_child_weight': [1],
    'reg_alpha': [2],
    'gamma': [0]
}

grid = ParameterGrid(params_grid)
best = 1

for params in grid:
    print params

{'reg_alpha': 2, 'colsample_bytree': 0.6, 'learning_rate': 0.05, 'min_child_weight': 1, 'n_estimators': 100, 'subsample': 0.6, 'max_depth': 7, 'gamma': 0}
{'reg_alpha': 2, 'colsample_bytree': 0.6, 'learning_rate': 0.5, 'min_child_weight': 1, 'n_estimators': 100, 'subsample': 0.6, 'max_depth': 7, 'gamma': 0}
{'reg_alpha': 2, 'colsample_bytree': 0.5, 'learning_rate': 0.05, 'min_child_weight': 1, 'n_estimators': 100, 'subsample': 0.6, 'max_depth': 7, 'gamma': 0}
{'reg_alpha': 2, 'colsample_bytree': 0.5, 'learning_rate': 0.5, 'min_child_weight': 1, 'n_estimators': 100, 'subsample': 0.6, 'max_depth': 7, 'gamma': 0}


In [17]:
grid

In [19]:
df = pd.read_csv('data/training.txt', delimiter=';', parse_dates=['time_interval_begin'], dtype={'link_ID': object})

In [20]:
df2 = df.head(100)

In [21]:
df2

link_ID        date time_interval_begin  travel_time  \
0   3377906280028510514  2017-03-01 2017-03-01 06:00:00     1.657881   
1   3377906280028510514  2017-03-01 2017-03-01 06:02:00     1.658394   
2   3377906280028510514  2017-03-01 2017-03-01 06:04:00     1.672953   
3   3377906280028510514  2017-03-01 2017-03-01 06:06:00     1.676887   
4   3377906280028510514  2017-03-01 2017-03-01 06:08:00     1.680537   
5   3377906280028510514  2017-03-01 2017-03-01 06:10:00     1.629241   
6   3377906280028510514  2017-03-01 2017-03-01 06:12:00     1.629241   
7   3377906280028510514  2017-03-01 2017-03-01 06:14:00     1.629241   
8   3377906280028510514  2017-03-01 2017-03-01 06:16:00     1.695692   
9   3377906280028510514  2017-03-01 2017-03-01 06:18:00     1.700773   
10  3377906280028510514  2017-03-01 2017-03-01 06:20:00     1.705794   
11  3377906280028510514  2017-03-01 2017-03-01 06:22:00     1.710754   
12  3377906280028510514  2017-03-01 2017-03-01 06:24:00     1.715654   
13  3377906280028510514  2017-03-01 2017-03-01 06:26:00     1.720495   
14  3377906280028510514  2017-03-01 2017-03-01 06:28:00     1.725276   
15  3377906280028510514  2017-03-01 2017-03-01 06:30:00     1.729998   
16  3377906280028510514  2017-03-01 2017-03-01 06:32:00     1.734662   
17  3377906280028510514  2017-03-01 2017-03-01 06:34:00     1.739268   
18  3377906280028510514  2017-03-01 2017-03-01 06:36:00     1.743815   
19  3377906280028510514  2017-03-01 2017-03-01 06:38:00     1.748305   
20  3377906280028510514  2017-03-01 2017-03-01 06:40:00     1.752738   
21  3377906280028510514  2017-03-01 2017-03-01 06:42:00     1.757114   
22  3377906280028510514  2017-03-01 2017-03-01 06:44:00     1.761434   
23  3377906280028510514  2017-03-01 2017-03-01 06:46:00     1.765697   
24  3377906280028510514  2017-03-01 2017-03-01 06:48:00     1.769905   
25  3377906280028510514  2017-03-01 2017-03-01 06:50:00     1.774057   
26  3377906280028510514  2017-03-01 2017-03-01 06:52:00     1.758337   
27  3377906280028510514  2017-03-01 2017-03-01 06:54:00     1.782196   
28  3377906280028510514  2017-03-01 2017-03-01 06:56:00     1.786184   
29  3377906280028510514  2017-03-01 2017-03-01 06:58:00     1.790118   
..                  ...         ...                 ...          ...   
70  3377906280028510514  2017-03-01 2017-03-01 08:20:00     1.923816   
71  3377906280028510514  2017-03-01 2017-03-01 08:22:00     1.856298   
72  3377906280028510514  2017-03-01 2017-03-01 08:24:00     1.856298   
73  3377906280028510514  2017-03-01 2017-03-01 08:26:00     1.856298   
74  3377906280028510514  2017-03-01 2017-03-01 08:28:00     1.945910   
75  3377906280028510514  2017-03-01 2017-03-01 08:30:00     1.933329   
76  3377906280028510514  2017-03-01 2017-03-01 08:32:00     1.935118   
77  3377906280028510514  2017-03-01 2017-03-01 08:34:00     1.936869   
78  3377906280028510514  2017-03-01 2017-03-01 08:36:00     1.938584   
79  3377906280028510514  2017-03-01 2017-03-01 08:38:00     1.940262   
80  3377906280028510514  2017-03-01 2017-03-01 08:40:00     1.941903   
81  3377906280028510514  2017-03-01 2017-03-01 08:42:00     2.041220   
82  3377906280028510514  2017-03-01 2017-03-01 08:44:00     2.054124   
83  3377906280028510514  2017-03-01 2017-03-01 08:46:00     2.054124   
84  3377906280028510514  2017-03-01 2017-03-01 08:48:00     2.054124   
85  3377906280028510514  2017-03-01 2017-03-01 08:50:00     1.791759   
86  3377906280028510514  2017-03-01 2017-03-01 08:52:00     1.791759   
87  3377906280028510514  2017-03-01 2017-03-01 08:54:00     1.824549   
88  3377906280028510514  2017-03-01 2017-03-01 08:56:00     2.041220   
89  3377906280028510514  2017-03-01 2017-03-01 08:58:00     2.079442   
90  3377906280028510514  2017-03-01 2017-03-01 13:00:00     1.902108   
91  3377906280028510514  2017-03-01 2017-03-01 13:02:00     1.740466   
92  3377906280028510514  2017-03-01 2017-03-01 13:04:00     1.840550   
93  3377906280028510514  2017-03-01 2017-03-01 13:06:00 

In [22]:
def bucket_data(lines):
    bucket = {}
    for line in lines:
        time_series = line[-2]
        bucket[time_series] = []
    for line in lines:
        time_series, y1 = line[-2:]
        line = np.delete(line, -2, axis=0)
        bucket[time_series].append(line)
    return bucket

In [23]:
valid_data = bucket_data(df2)

In [25]:
valid_data.keys()

['e', 'g', 'I', 'm', 'o', 'n', '1', 'i', 't', '.', '_']

In [ ]:
df_test = df_test[valid_feature].values

In [26]:
lagging = 5
df = pd.read_csv('data/training.txt', delimiter=';', parse_dates=['time_interval_begin'], dtype={'link_ID': object})
lagging_feature = ['lagging%01d' % e for e in range(lagging, 0, -1)]  # 生成lagging特征
base_feature = [x for x in df.columns.values.tolist() if x not in ['time_interval_begin', 'link_ID', 'link_ID_int',
                                                                   'date', 'travel_time', 'imputation1',
                                                                   'minute_series', 'area', 'hour_en', 'day_of_week']]
base_feature = [x for x in base_feature if x not in lagging_feature]
train_feature = list(base_feature)
train_feature.extend(lagging_feature)
valid_feature = list(base_feature)
valid_feature.extend(['minute_series', 'travel_time'])
print train_feature

['length', 'vacation', 'day_of_week_en', 'week_hour_1.0,1.0', 'week_hour_1.0,2.0', 'week_hour_1.0,3.0', 'week_hour_2.0,1.0', 'week_hour_2.0,2.0', 'week_hour_2.0,3.0', 'week_hour_3.0,1.0', 'week_hour_3.0,2.0', 'week_hour_3.0,3.0', 'links_num_0.0,1.0', 'links_num_1.0,1.0', 'links_num_1.0,2.0', 'links_num_1.0,3.0', 'links_num_1.0,4.0', 'links_num_2.0,1.0', 'links_num_2.0,2.0', 'links_num_3.0,1.0', 'links_num_4.0,1.0', 'links_num_other', 'width_3', 'width_6', 'width_9', 'width_12', 'width_15', 'link_ID_en', 'lagging5', 'lagging4', 'lagging3', 'lagging2', 'lagging1']


In [27]:
df_test = df.head(100)
df_test = df_test[valid_feature].values

In [30]:
valid_data = bucket_data(df_test)

In [50]:
range(120, 120 + lagging * 2, 2)

[120, 122, 124, 126, 128]

In [36]:
df_test[1][-2:]

array([ 2.        ,  1.65839411])

In [37]:
last = [[] for i in range(len(valid_data[valid_data.keys()[0]]))]

In [38]:
last

[[], []]

In [47]:
valid_data[2.0]

[array([ 48.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  46.        ,   1.65839411]),
 array([ 48.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  46.        ,   1.74046617])]

In [49]:
valid_data

{0.0: [array([ 48.        ,   0.        ,   1.        ,   1.        ,
           0.        ,   0.        ,   0.        ,   0.        ,
           0.        ,   0.        ,   0.        ,   0.        ,
           0.        ,   1.        ,   0.        ,   0.        ,
           0.        ,   0.        ,   0.        ,   0.        ,
           0.        ,   0.        ,   1.        ,   0.        ,
           0.        ,   0.        ,   0.        ,  46.        ,   1.65788099]),
  array([ 48.        ,   0.        ,   1.        ,   0.        ,
           1.        ,   0.        ,   0.        ,   0.        ,
           0.        ,   0.        ,   0.        ,   0.        ,
           0.        ,   1.        ,   0.        ,   0.        ,
           0.        ,   0.        ,   0.        ,   0.        ,
           0.        ,   0.        ,   1.        ,   0.        ,
           0.        ,   0.        ,   0.        ,  46.        ,   1.90210753])],
 2.0: [array([ 48.        ,   0.        ,   1.      